import type {Theme} from './theme';

const themes: Theme[] = [
  {
    id: 1,
    storeName: '키이스케이프 LOG_IN 1',
    name: '크리쳐 - 신인류의 탄생',
    status: 'operating',
    difficulty: 3,
    playTimeMinutes: 65,
    genres: ['SF', '스릴러'],
  },
  {
    id: 2,
    storeName: '키이스케이프 LOG_IN 1',
    name: '미드나잇 익스프레스',
    status: 'operating',
    difficulty: 4,
    playTimeMinutes: 70,
    genres: ['추리', '미스터리'],
  },
  {
    id: 3,
    storeName: '비트포비아 홍대점',
    name: '저주받은 인형',
    status: 'operating',
    difficulty: 3,
    playTimeMinutes: 60,
    genres: ['추리', '미스터리'],
  },
  {
    id: 4,
    storeName: '코드케이 강남점',
    name: '셜록의 서재',
    status: 'operating',
    difficulty: 5,
    playTimeMinutes: 75,
    genres: ['추리', '탐정'],
  },
  {
    id: 5,
    storeName: '넥스트에디션 신촌점',
    name: '타임루프',
    status: 'new',
    difficulty: 4,
    playTimeMinutes: 60,
    genres: ['SF'],
  },
  {
    id: 6,
    storeName: '마스터키 홍대점',
    name: '좀비 바이러스',
    status: 'operating',
    difficulty: 3,
    playTimeMinutes: 70,
    genres: ['호러', 'SF'],
  },
  {
    id: 7,
    storeName: '비밀의방 삼성점',
    name: '비밀의 저택',
    status: 'closed',
    difficulty: 2,
    playTimeMinutes: 60,
    genres: ['어드벤처', '미스터리'],
  },
  {
    id: 8,
    storeName: '제로월드 건대점',
    name: '우주 정거장',
    status: 'closing',
    difficulty: 4,
    playTimeMinutes: 75,
    genres: ['SF', '어드벤처'],
  },
  {
    id: 9,
    storeName: '어메이징 브레이킹 신림점',
    name: '뱅크 하이스트',
    status: 'closed',
    difficulty: 5,
    playTimeMinutes: 80,
    genres: ['범죄', '액션'],
  },
  {
    id: 10,
    storeName: '리얼월드 이대점',
    name: '마법학교의 비밀',
    status: 'operating',
    difficulty: 2,
    playTimeMinutes: 60,
    genres: ['판타지'],
  },
  {
    id: 11,
    storeName: '셜록홈즈 대학로점',
    name: '잃어버린 기록',
    status: 'operating',
    difficulty: 4,
    playTimeMinutes: 70,
    genres: ['추리', '드라마'],
  },
  {
    id: 12,
    storeName: '코드케이 강남점',
    name: '라스트 시그널',
    status: 'operating',
    difficulty: 3,
    playTimeMinutes: 65,
    genres: ['SF', '미스터리'],
  },
  {
    id: 13,
    storeName: '넥스트에디션 신촌점',
    name: '심야 병동',
    status: 'operating',
    difficulty: 4,
    playTimeMinutes: 75,
    genres: ['호러'],
  },
  {
    id: 14,
    storeName: '비트포비아 홍대점',
    name: '카지노 로얄',
    status: 'new',
    difficulty: 3,
    playTimeMinutes: 60,
    genres: ['범죄', '액션'],
  },
  {
    id: 15,
    storeName: '마스터키 홍대점',
    name: '사라진 연구원',
    status: 'operating',
    difficulty: 5,
    playTimeMinutes: 80,
    genres: ['스릴러', '추리'],
  },
];

export {themes};
