name: PR labeler

on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Check Labels
        id: labeler
        uses: jimschubert/labeler-action@e6fb93f2d64d8b0b78d208456f349e9e00698a5d # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config_path: .github/labeler.yml
